### PR TITLE
Use KJVA instead of KJV as reference for versification mappings.

### PR DESCRIPTION
**Pull request by UnasZole**
This PR fully implements #12 .

Specifically : 
- Refactor the SystemKJVA class to avoid duplication of data with SystemKJV (ie directly call data from SystemKJV, and only append the additional books via array concatenation).
- Change VersificationToKJVMapper to use KJVA internally instead of KJV. (No renaming to avoid breaking potential users)
- Fix behaviour of "unmap" for verses that exist in KJVA but not in the target versification (since now all the deuterocanonical books are in this situation) : accurately return an empty unmapped interval. This avoids the need to explicitly specify the absent books in all existing mapping files (and notably avoids the need to create a mapping file from KJV to KJVA entirely since the only differences are absent books).
- Add Catholic and Catholic2 mapping properties files, and update unit tests to rely on these real files. 

In order to validate properly if the verses exist in the target versification, I decided to define and implement an additional method VerseKey#isValidIn that checks if the key is valid in a different versification. This new method should be enough to check if the VerseKey#reversify method can be called. (reversify had a big warning in Javadoc that it was not safe, but no way of actually checking).

Regarding the Catholic/Catholic2 versification mapping files, note that I've just made these files in a few hours of work these last few days, comparing the text from the KJVA module with other catholic bibles I have. They are the most accurate I could get, given that for some books (Tobit in particular) the split in verses varies wildly even between catholic bibles - for these cases, I tried to choose the verse split that was "most consensual" among the bibles at my disposal.

### CODE REVIEW

**Comment by UnasZole** [comment]
For what it's worth, this PR attempts to do the minimal changes to avoid breaking existing uses - notably avoid impact on andbible.

I'd be interested in doing a much bigger refactoring later on, though (if you are open to it), as there are a number of small design issues.
In particular around the multiplicity of the keys : for example, VersificationToKJVMapper.unmap accepts a QualifiedKey, which may be any kind of VerseKey. The Javadoc implies it's supposed to be a single verse... But the VersificationMapper actually sends the output of the first mapping directly, which may be a verse range !
This lack of clarity in the interfaces kind of screams to me that the API around these keys should be reworked.

Would you be open to bigger future PRs (meaning as well needed changes in the andbible code), or would you rather not break the current API ?

**Comment by tuomas2** [comment]
> Would you be open to bigger future PRs (meaning as well needed changes in the andbible code), or would you rather not break the current API ?

I'm open to improvements but I then assume that you also make necessary changes to AndBible and test them properly and take some responsibility of fixing arising issues also. I'm not sure if I dare to take bigger changes directly to my current fast production deployment cycle (1 week in Google Play beta channel and then to production); but will consider that later on after seeing the changes. 

I can't promise I will do very in-depth review to larger prs (I'm not even super familiar with JSword code), but will most likely accept it if it looks OK and you have unit tests for your changes.

**Comment by tuomas2** [comment]
Are you using jsword in some other app other than AndBible or are you making improvements primarily for AndBible?

**Comment by tuomas2** [comment]
Created develop branch and changed target of this PR there first.

**Comment by tuomas2** [comment]
Changes look good to me. Merging to develop. Will merge develop to master when taking new code to AndBible. 
Creating ticket about it: https://github.com/AndBible/and-bible/issues/3173

**Comment by UnasZole** [comment]
Thanks for the merge !

> I'm open to improvements but I then assume that you also make necessary changes to AndBible and test them properly and take some responsibility of fixing arising issues also.

Sure, I understand !
For the time being, I'll avoid any breaking changes then - but when I have time to setup a proper environment to build and test andbible myself, I might start proposing bigger changes.

> Are you using jsword in some other app other than AndBible or are you making improvements primarily for AndBible?

A little bit of both :-D

This versification mapping update is something that I hope to see well integrated in AndBible itself, to make it easier to read and compare two translations that use different versification systems. (For example, read and compare Daniel 3 between a Catholic and a KJVA bible)
When I do take time to set up a test environment for AndBible on my machine, I'll probably start to open some PRs related to this kind of features (just like the ticket I opened about eusebian Gospel parallels as well).

But I'm also writing a small tool of my own which uses JSword. It's a program to help parsing and converting bibles from HTML pages or text documents into OSIS, to then make it easy to generate sword modules and load them into AndBible. And I use JSword specifically to help detect the versification system of the bible I'm parsing.

**Pull request merged**
